use std::fs;

use serde_json::json;

use std::path::Path;

use crate::config::IexConfig;
use crate::paths::generated_dir;
use crate::util::write_if_changed;

pub fn generate_constants(cfg: &IexConfig, project_dir: &Path) {
    let gen = generated_dir();
    fs::create_dir_all(&gen).unwrap();

    let project_abs = fs::canonicalize(project_dir)
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| project_dir.to_string_lossy().into_owned());

    let app_config = json!({
        "name": cfg.name,
        "displayName": cfg.display_name,
        "bundleId": cfg.bundle_id,
        "scheme": cfg.scheme,
        "port": cfg.port,
        "rnVersion": cfg.rn_version,
        "projectDir": project_abs,
    });

    let build_info = json!({
        "iexVersion": env!("CARGO_PKG_VERSION"),
    });

    let content = format!(
        "// Auto-generated by iex CLI. Do not edit.\n\
         globalThis.__IEX_APP_CONFIG__ = {};\n\
         globalThis.__IEX_BUILD_INFO__ = {};\n",
        serde_json::to_string_pretty(&app_config).unwrap(),
        serde_json::to_string_pretty(&build_info).unwrap(),
    );

    write_if_changed(&gen.join("constants.generated.js"), &content);
}
