use std::fs;

use crate::config::IexConfig;
use crate::metro::render_metro_config;
use crate::paths::{apps_dir, generated_dir, packages_dir, shell_dir};
use crate::util::{js_string, write_if_changed};

/// Generate the launcher entry. The launcher *is* the iExpo bundle the shell
/// boots into; per-app code is no longer baked in here. Apps come down at
/// runtime from `serverUrl`'s `/apps` catalog (see `iex publish-app`) and the
/// native side swaps the bundle when the user picks one.
pub fn generate_hub_entry(shell_module_name: &str, server_url: &str) {
    let gen = generated_dir();
    fs::create_dir_all(&gen).unwrap();

    let content = format!(
        "import './constants.generated';\n\
         import {{ AppRegistry }} from 'react-native';\n\
         import {{ Hub }} from 'iex/hub';\n\n\
         function Launcher() {{ return <Hub serverUrl={{{server_q}}} />; }}\n\n\
         AppRegistry.registerComponent({module_q}, () => Launcher);\n",
        server_q = js_string(server_url),
        module_q = js_string(shell_module_name),
    );
    write_if_changed(&gen.join("index.generated.js"), &content);
}

pub fn generate_hub_metro() {
    let gen = generated_dir();
    let shell_abs = fs::canonicalize(shell_dir()).unwrap_or_else(|_| shell_dir());
    let packages_iex = packages_dir().join("iex");
    // apps/ is included so `iex publish-app <id>` (which reuses this metro
    // config) can resolve files under any app dir. The launcher itself
    // doesn't import from apps/, so Metro won't pull them into its bundle.
    let apps = apps_dir();

    let content = render_metro_config(&[&shell_abs, &packages_iex, &apps], &packages_iex);
    write_if_changed(&gen.join("metro.config.generated.js"), &content);
}

pub fn generate_hub_constants(platform_cfg: &IexConfig) {
    use serde_json::json;

    let gen = generated_dir();
    fs::create_dir_all(&gen).unwrap();

    let project_abs = apps_dir().to_string_lossy().into_owned();
    let app_config = json!({
        "name": platform_cfg.name,
        "displayName": platform_cfg.display_name,
        "bundleId": platform_cfg.bundle_id,
        "scheme": platform_cfg.scheme,
        "port": platform_cfg.port,
        "rnVersion": platform_cfg.rn_version,
        "projectDir": project_abs,
        "isHub": true,
    });
    let build_info = json!({ "iexVersion": env!("CARGO_PKG_VERSION") });

    let content = format!(
        "// Auto-generated by iex CLI (hub mode). Do not edit.\n\
         globalThis.__IEX_APP_CONFIG__ = {};\n\
         globalThis.__IEX_BUILD_INFO__ = {};\n",
        serde_json::to_string_pretty(&app_config).unwrap(),
        serde_json::to_string_pretty(&build_info).unwrap(),
    );
    write_if_changed(&gen.join("constants.generated.js"), &content);
}

pub fn platform_config() -> IexConfig {
    let mut cfg = IexConfig::default();
    cfg.display_name = "iExpo".to_string();
    cfg
}

/// Configure the shell to host the launcher. Run `ensure_shell(&platform_config())`
/// first to lay down the entry-point stubs.
pub fn configure_hub(server_url: &str) {
    println!("🌐 Catalog server: {server_url}");
    let platform = platform_config();
    generate_hub_constants(&platform);
    generate_hub_entry(&platform.name, server_url);
    generate_hub_metro();
}
